### ISSUE TITLE
Ajout d'une licence (MIT?)

### ISSUE THREAD

**Issue by bzg** [etalab/de-dpe-processing#8]
Hello !  Pour ce dépôt, je pense qu'une licence MIT serait de bon aloi - sinon une autre licence permissive parmi [cette liste](https://www.data.gouv.fr/fr/licences).  N'hésite pas à me dire si ça t'aide que je fasse la PR.  Merci !

**Comment by geoffreyaldebert** [comment]
Salut Bastien, merci pour ton issue.

Je suis ok le MIT est adapté.

@AntoineBreitwillerCSTB : si c'est ok pour toi, j'ajoute la licence au repo.

**Comment by AntoineBreitwillerCSTB** [comment]
Oui merci je veux bien que tu l’ajoute et comme ça si c’est adapté à nos autres répo open source je copierais le fichier de License vers nos autres répos open source.

De : Geoffrey Aldebert ***@***.***>
Envoyé : jeudi 1 avril 2021 14:35
À : etalab/de-dpe-processing ***@***.***>
Cc : BREITWILLER Antoine ***@***.***>; Mention ***@***.***>
Objet : Re: [etalab/de-dpe-processing] Ajout d'une licence (MIT?) (#8)


Salut Bastien, merci pour ton issue.

Je suis ok le MIT est adapté.

@AntoineBreitwillerCSTB<https://github.com/AntoineBreitwillerCSTB> : si c'est ok pour toi, j'ajoute la licence au repo.

**Comment by geoffreyaldebert** [comment]
License ajouté ! Merci à tous, je close l'issue.
